import type TelegrafPKG from "telegraf";
import type { Update } from "typegram";

import BackCommand from "../commands/back";
import BackToProvincialBranchListCommand from "../commands/backToProvincialBranchList";
import StartCommand from "../commands/start";
import RegisterCommand from "../commands/register";
import CustomerIdCommand from "../commands/customerId";
import BalanceCommand from "../commands/balance";
import StatementsCommand from "../commands/statements";
import AppointmentsCommand from "../commands/appointments";
import CheckUpcomingAppointmentCommand from "../commands/checkUpcomingAppointments";
import BookAppointmentCommand from "../commands/bookAppointment";
import ShopOnlineCommand from "../commands/shopOnline";
import RequestACallbackCommand from "../commands/requestACallback";
import BranchLocatorCommand from "../commands/branchLocator";
import ProvincialBranchListCommand from "../commands/provincialBranchList";
import EasternCapeBranchesBotCommand from "../commands/easternCapeBranches";
import FreeStateBranchesBotCommand from "../commands/freeStateBranches";
import GautengBranchesBotCommand from "../commands/gautengBranches";
import KwazuluNatalBranchesBotCommand from "../commands/kwazuluNatalBranches";
import LimpopoBranchesBotCommand from "../commands/limpopoBranches";
import MpumalangaBranchesBotCommand from "../commands/mpumalangaBranches";
import NorthernCapeBranchesBotCommand from "../commands/northernCapeBranches";
import NorthWestBranchesBotCommand from "../commands/northWestBranches";
import WesternCapeBranchesBotCommand from "../commands/westernCapeBranches";
import FindClosestBranchCommand from "../commands/findClosestBranch";
import ShareLocationCommand from "../commands/shareLocation";
import SocialMediaCommand from "../commands/socialMedia";
import FacebookCommand from "../commands/facebook";
import InstagramCommand from "../commands/instagram";
import MellinsChannelLinkCommand from "../commands/mellinsChannelLink";
import JoinMellinsChannelCommand from "../commands/joinMellinsChannel";
import ShareContactCommand from "../commands/shareContact";

function registerBotCommands(bot: TelegrafPKG.Telegraf<TelegrafPKG.Context<Update>>) {
  BackCommand(bot);
  BackToProvincialBranchListCommand(bot);
  StartCommand(bot);
  RegisterCommand(bot);
  CustomerIdCommand(bot);
  BalanceCommand(bot);
  StatementsCommand(bot);
  AppointmentsCommand(bot);
  CheckUpcomingAppointmentCommand(bot);
  BookAppointmentCommand(bot);
  ShopOnlineCommand(bot);
  RequestACallbackCommand(bot);
  BranchLocatorCommand(bot);
  ProvincialBranchListCommand(bot);
  EasternCapeBranchesBotCommand(bot);
  FreeStateBranchesBotCommand(bot);
  GautengBranchesBotCommand(bot);
  KwazuluNatalBranchesBotCommand(bot);
  LimpopoBranchesBotCommand(bot);
  MpumalangaBranchesBotCommand(bot);
  NorthernCapeBranchesBotCommand(bot);
  NorthWestBranchesBotCommand(bot);
  WesternCapeBranchesBotCommand(bot);
  FindClosestBranchCommand(bot);
  ShareLocationCommand(bot);
  MellinsChannelLinkCommand(bot);
  JoinMellinsChannelCommand(bot);
  SocialMediaCommand(bot);
  FacebookCommand(bot);
  InstagramCommand(bot);
  ShareContactCommand(bot);
}

export default registerBotCommands;
