version: "2.4"

services:
  mellins-bot:
    container_name: mellins-bot
    image: asjas/mellins-bot-server:latest
    restart: always
    depends_on:
      - db
    network_mode: host
  db:
    container_name: db
    image: postgres:14.1-alpine
    volumes:
      - db-data:/var/lib/postgresql
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: ${FASTIFY_DB_USER}
      POSTGRES_PASSWORD: ${FASTIFY_DB_PASS}
      POSTGRES_DB: ${FASTIFY_DB}

volumes:
  db-data:
    external: false
