version: "2.4"

services:
  webapp:
    container_name: api
      build:
        context: .
      depends_on:
        - redis
        - db
  redis:
    container_name: redis
    image: redis:6.2.4-alpine
    restart: always
  db:
    container_name: db
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: fastify
      POSTGRES_PASSWORD: fastify
      POSTGRES_DB: fastify

volumes:
  redis_data:
  db_data:
