version: "2.4"

services:
  redis:
    container_name: mellins-bot-redis
    image: redis:6.2.6-alpine
    command: redis-server --requirepass ${REDIS_AUTH}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    restart: always
  db:
    container_name: mellins-bot-db
    image: postgres:14.0-alpine
    ports:
      - ${FASTIFY_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: ${FASTIFY_DB_USER}
      POSTGRES_PASSWORD: ${FASTIFY_DB_PASS}
      POSTGRES_DB: ${FASTIFY_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis-data:
    external: false
  db-data:
    external: false
