version: "2.4"

services:
  webapp:
    container_name: mellins-bot-api
      build:
        context: .
      depends_on:
        - mellins-db
  db:
    container_name: mellins-db
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: fastify
      POSTGRES_PASSWORD: fastify
      POSTGRES_DB: fastify
