version: "2.4"

services:
  mellins-bot:
    container_name: mellins-bot
    image: asjas/mellins-bot:latest
    restart: always
    ports:
      - 8080:6500
    depends_on:
      - redis
      - db
    networks:
      - mellins-bot
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    command: redis-server --requirepass ${REDIS_AUTH}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - mellins-bot
  db:
    container_name: db
    image: postgres:14.0-alpine
    ports:
      - ${FASTIFY_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql
    restart: always
    networks:
      - mellins-bot
    environment:
      POSTGRES_USER: ${FASTIFY_DB_USER}
      POSTGRES_PASSWORD: ${FASTIFY_DB_PASS}
      POSTGRES_DB: ${FASTIFY_DB}

volumes:
  redis-data:
    external: false
  db-data:
    external: false

networks:
  mellins-bot:
